[package]
name = "proser"
version = "0.0.0-dev"
edition = "2021"
license = "MIT"

[dependencies]
serde = "1"
thiserror = "1.0.37"

[dev-dependencies]
serde_bytes = "0.11"
serde = { version="1", features=["derive"] }
bincode = "1"
serde_json = "1"
prost = "0.11"
prost-build = "0.11"
fcode = "1.0.0"
